### ISSUE TITLE
traversing gems

### ISSUE THREAD

**Issue by JohnMorales** [tpope/vim-bundler#37]
Hi quick question,

When I gf in a bundled gem, and I want to gf into a dependency to that gem I cannot get there. I know there must be something that I'm missing, but don't know what I need. Basically vim-bundle correctly changes the path when it goes to the bundled gem, but at that point I don't have all gems paths that I originally had. Is there a way to keep the paths, instead of clearing them, or is there a command to automatically add all the gems in a gem dir when I'm in one?

for example

gf in a file in my project
goes to sinatra/base in gem sinatra
in there I gf on line "include Rack::Utils"

and get "Can't find file Rack/Utils.rb"

My paths are now (which doesn't include any gems):
path=~/.rbenv/versions/2.0.0-p353/lib/ruby/site_ruby/2.0.0,
~/.rbenv/versions/2.0.0-p353/lib/ruby/site_ruby/2.0.0/x86_64-darwin13.0.1,
~/.rbenv/versions/2.0.0-p353/lib/ruby/site_ruby,
~/.rbenv/versions/2.0.0-p353/lib/ruby/vendor_ruby/2.0.0,
~/.rbenv/versions/2.0.0-p353/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin13.0.1,
~/.rbenv/versions/2.0.0-p353/lib/ruby/vendor_ruby,
~/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0,
~/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/x86_64-darwin13.0.1

**Comment by nikhgupta** [comment]
I wanted exactly the same behaviour, i.e. when I navigate away to Gem directories from my Rails project, I should be able to dig deeper into the tags. Here is what I am doing (o'course this is hackish):

    augroup gem_ctags
      au!
      let $GEMPATH__LOCAL = system("gem env home")[:-2] . "/gems"
      au BufEnter $GEMPATH__LOCAL/**/*.rb setl tags+=$GEMPATH__LOCAL/*/tags
      au BufLeave $GEMPATH__LOCAL/**/*.rb setl tags-=$GEMPATH__LOCAL/*/tags
    augroup END

**Comment by tpope** [comment]
See #27 for fresh thoughts on this.
