### ISSUE TITLE
Support new filenames

### ISSUE THREAD

**Issue by andremedeiros** [tpope/vim-bundler#40]
As of Bundler 1.9, for a number of reasons we've changed the default filenames where your application dependencies are expressed. Also, the old `Gemfile` and `Gemfile.lock` files will be deprecated as of Bundler 2.0

As such, we've changed:
- `Gemfile` to `gems.rb`
- `Gemfile.lock` to `gems.locked`

It would be great if the plugin could start supporting these new files.

**Comment by tpope** [comment]
Awesome, this was much anticipated.

**Comment by andremedeiros** [comment]
:heart: thanks for the quick turnaround!

**Comment by shahroon** [comment]
It would be nice if someone just enlist all those reasons that forced this change.

**Comment by tpope** [comment]
https://github.com/bundler/bundler/issues/694
