### ISSUE TITLE
Add support for Ruby 2.5.0

### ISSUE THREAD

**Issue by rosenfeld** [tpope/vim-bundler#46]
`ubygems.rb` is no longer available in Ruby 2.5.0, so this command fails:

https://github.com/tpope/vim-bundler/blob/master/plugin/bundler.vim#L356

`ruby -rubygems -e ...`

Could you please add support for Ruby 2.5.0?

**Comment by tpope** [comment]
Glad they got rid of that dumb file, but why wasn't there a deprecation warning? :(

**Comment by rosenfeld** [comment]
Thank you so much! That was quick :)
