### ISSUE TITLE
Cannot find gems installed with direnv

### ISSUE THREAD

**Issue by eloyesp** [tpope/vim-bundler#49]
I'm using [direnv](https://direnv.net/) so gems are installed in `.direnv/ruby`. This is implemented setting the `GEM_HOME` environment variable.

With that change, bundle can find the gems (`bundle list --paths` lists all the files, and the project is working), but vim-bundler cannot find any gem.

Any ideas if that can be fixed?

**Comment by tpope** [comment]
Is `$GEM_HOME` set *inside* Vim? Does `:!bundle list --paths` work?

**Comment by eloyesp** [comment]
yes, vim is initialized within the environment and `:!bundle list --paths`
works as expected.

**Comment by eloyesp** [comment]
`GEM_PATH` is not set, 

`ruby -rrubygems -e 'puts(*Gem.path)'` returns the direnv path in the last position...

~~~
/home/eloyesp/.gem/ruby/2.5.0
/var/lib/gems/2.5.0
/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0
/usr/share/rubygems-integration/2.5.0
/usr/share/rubygems-integration/all
/home/eloyesp/projects/verify/bank_party/.direnv/ruby
~~~

**Comment by eloyesp** [comment]
May be it could use `bundle list --paths` to get the list of folders? It makes sense in `vim-bundler`.

**Comment by tpope** [comment]
Depending on bundle size and Ruby version that can be prohibitively show.

I guess I need to see the entirety of `bundler#project()`. Easiest way is probably to install [scriptease.vim](/tpope/vim-scriptease) and do `:Verbose PP bundler#project()`.

**Comment by eloyesp** [comment]
Here it is https://pastebin.com/iXpdxSiT I cannot find any path there.

**Comment by tpope** [comment]
Okay, that lets me rule out some things at least. I think you're gonna have to edit the plugin to `:echo gem_paths` after https://github.com/tpope/vim-bundler/blob/9b050471b2168b2f58a239d44b0711557cd8a975/plugin/bundler.vim#L390 and see what went wrong.

**Comment by eloyesp** [comment]
It seems to be fixed with the last release :/
