### ISSUE TITLE
need a file to be opened to works(no command recognized if not)... and all the time errors happen. [resolved]

### ISSUE THREAD

**Issue by jerome-diver** [tpope/vim-bundler#52]
cd  to my rails project dir
then just open vim (vim command)
:help bundler

said: Error detected function <SNR>22_BufAddHandler[8]...<SNR>22_AutoUpdate[35]...<SNR>22_StartExplorer : ligne 81
"bundler.txt" 76L, 3267C

:Bopen doesn't do anything (unrecognized command)

installed in ~/.vim/plugins/vim-bundler/ directory from your git package with Vim-Plug Vim plugin manager.

If now i open a file who is inside this rails project, then use a bundler-vim command, error appears again, but command is recognized and Gemfile open in a new tab.

**Comment by tpope** [comment]
Open a file first.

That error message is from another plugin. Look for script number 22 in `:scriptnames`.

**Comment by tpope** [comment]
The short answer is there's not a good way to do it. You can use `VimEnter` to handle the first empty buffer after Vim starts. Some of my other plugins do that.
