### ISSUE TITLE
neovim 0.8.0 filetype.lua Unknown function

### ISSUE THREAD

**Issue by mario-amazing** [tpope/vim-bundler#56]
After I've updated to neovim 0.8.0 I started to get this error:
<img width="1888" alt="Screenshot 2022-10-26 at 04 39 35" src="https://user-images.githubusercontent.com/9537753/197914460-efacca8e-8fca-4c3b-b09e-667a12968af2.png">

**Comment by tpope** [comment]
Sounds like a different manifestation of https://github.com/tpope/vim-rake/issues/38. Even with the added context, I'm not really sure what this could be. Can you check `:scriptnames` and see what script number 5 is?

**Comment by mario-amazing** [comment]
ofc
` 5: ~/.config/nvim/autoload/plug.vim`
