### ISSUE TITLE
Strange Characters on Startup with Projectionist

### ISSUE THREAD

**Issue by dmcinnes** [tpope/vim-bundler#58]
I've been seeing these weird characters on vim startup that remain on the screen until I do a CTRL-L:
```
^[[?12;4$y
```
I've been able to narrow it down to loading the latest vim-projectionist with the latest vim-bundler using vim-plugged. I've removed all the other plugins, and these characters only show up if bundler and projectionist are loaded together -- remove either plugin and they disappear.

I'm running the latest vim compiled by Homebrew:
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 15 2022 18:56:17)
macOS version - x86_64
Included patches: 1-472
Compiled by Homebrew
```

**Comment by tpope** [comment]
1. Did you try disabling not just other plugins, but your vimrc?
2. Can you confirm you don't have a `.zshenv`? (A random escape code does smell a bit like a misbehaving shell during `system()`.)
3. Does it always happen, or only when you start Vim from a directory with Bundler?
4. If the latter, does it happen if Projectionist activates for a different reason? (e.g., `echo '{}' > .projections.json; vim`)
5. Can you try on the latest stable version of both plugins and see if the same issue occurs? If so, narrowing down when exactly it broke would help to pinpoint the problem.
