### ISSUE TITLE
bundler return paths incorrectly

### ISSUE THREAD

**Issue by jiz4oh** [tpope/vim-bundler#59]
Hi @tpope, I am using rbenv as my ruby version manager, and I found a bug that the bundler does not work as expected if I open a ruby file from another directory.

the reproducing steps as below:
1.  install rbenv and has at lease two different ruby versions
2. install `vim-rbenv` and `vim-bundler`
3. create a temp directory with `.ruby-version` and `Gemfile`
4. specify a ruby version that different from the global one in the temp dire
5. open some files from another dir e.g. HOME dir

I think the issue is [here](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L397-L403), system is called in the cwd, not the correct dir which should consist with the `Gemfile`.

**Comment by jiz4oh** [comment]
sorry, it's caused by the macos loading rbenv incorrectly in `system call`

**Comment by jiz4oh** [comment]
the core reason is I am also using `direnv` which set the `$PATH` from cwd and the `$PATH` is force specified by [here](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L389)

**Comment by tpope** [comment]
> I think the issue is [here](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L397-L403), system is called in the cwd, not the correct dir which should consist with the `Gemfile`.

Whatever the issue is, it's not that. The current directory is changed [2 lines above "here"](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L395).

> the core reason is I am also using `direnv` which set the `$PATH` from cwd and the `$PATH` is force specified by [here](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L389)

`direnv` works by altering how `cd` works in your shell interactively (e.g., in `.bashrc`). Vim isn't an interactive shell. Vim isn't your shell, so we **can't** support this, except maybe if we were to completely reimplement `direnv`, from scratch, in Vim Script.

`rbenv`, by contrast, is very easy to support, because instead of hooking into your shell, it alters the behavior of `ruby` itself. This is very easy to support.

**Comment by tpope** [comment]
Instead of `direnv`, you might try [`mise`](https://mise.jdx.dev/). It can use the same model as `rbenv`, which means it works with Bundler.vim, and has support for a lot of the same features as `direnv`. It's what I use.

**Comment by jiz4oh** [comment]
Hi @tpope, i also checked the [direnv.vim](https://github.com/direnv/direnv.vim) and found it's loading new $PATH [asynchronously](https://github.com/direnv/direnv.vim/blob/ab2a7e08dd630060cd81d7946739ac7442a4f269/autoload/direnv.vim#L89) by [DirChanged](https://github.com/direnv/direnv.vim/blob/ab2a7e08dd630060cd81d7946739ac7442a4f269/plugin/direnv.vim#L30) event, so there are 3 choices for me:

1. remove or replace direnv
2. reload vim-bundler after new $PATH is set(there is a [event](https://github.com/direnv/direnv.vim/blob/ab2a7e08dd630060cd81d7946739ac7442a4f269/autoload/direnv.vim#L23) is fired)
3. loading vim-bundler without the [$PATH](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L389)

the last 2 ways need your support, the first way needs the [`setup`](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L216C11-L216C20) function be public that I can trigger it by me, the second way need you to give me some power to control the [`prefix`](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L389) behavior.

could you help consider this proposal? I hope this proposal won't add to your maintenance burden.

**Comment by tpope** [comment]
Vim doesn't recursively call autocommands by default, and since Bundler detection happens inside an autocommand, it's not going to trigger those `DirChanged` events. There is a solution for this: see `:help autocmd-nested`. You could try adding `++nested` to [these autocommands](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L249-L254) and see if that fixes it.

**Comment by jiz4oh** [comment]
hi @tpope, I have tested the `++nested` flag and it works with the [synchronized](https://github.com/direnv/direnv.vim/blob/ab2a7e08dd630060cd81d7946739ac7442a4f269/autoload/direnv.vim#L108-L112) hook, but unfortunately the hook is [asynchronously](https://github.com/direnv/direnv.vim/blob/ab2a7e08dd630060cd81d7946739ac7442a4f269/autoload/direnv.vim#L96-L106) in most cases. I need a stable way to trigger it with `bundler`, a possible way is expose the [setup](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L216C11-L216C20) or the [Detect](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L196) that let me trigger redetect bundle after new `$PATH` is set

**Comment by tpope** [comment]
The result is cached, so exposing `s:Setup` or `s:Detect` wouldn't have an effect by itself.

More fundamentally, global state and asynchronous code do not and cannot reliably be mixed. If your goal is to hook direnv's asynchronous callback up to Bundler.vim's usage of global environment variables, you _will_ create race conditions.

A low effort solution would be to add an option to direnv to always use the synchronous behavior. This will make `:cd` slower. If you're lucky, it will still be fast enough.

A high effort solution would be some sort of way to hand off the the environment from direnv to bundler.vim without going through the globals. Then we don't need to rely on the `:cd` for the environment at all. There's a lot of forms this could take. I'd prefer one that didn't couple me to direnv.vim specifically.

I'm also open to making bundler.vim more asynchronous, if it helps. On its own, it would not help.

**Comment by jiz4oh** [comment]
> More fundamentally, global state and asynchronous code do not and cannot reliably be mixed. If your goal is to hook direnv's asynchronous callback up to Bundler.vim's usage of global environment variables, you will create race conditions.
>  
> A low effort solution would be to add an option to direnv to always use the synchronous behavior. This will make :cd slower. If you're lucky, it will still be fast enough.

I really appreciate your helpful and patient response. I'll try my best to push `direnv.vim` to add an option to use the synchronous behavior.

And I found the [`$GEM_APTH`](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L383-L384) can be set before. 

So there the only issue here is [`abi_version`](https://github.com/tpope/vim-bundler/blob/c261509e78fc8dc55ad1fcf3cd7cdde49f35435c/plugin/bundler.vim#L402C13-L402C24), could we consider get the ruby version by `b:ruby_version` or another variable e.g. `$RUBY_VERSION` or read it from `Gemfile.lock` first. It's not impact many users I think.

What are your thoughts on this proposed solution?
